kind: Deployment
apiVersion: apps/v1
metadata:
  name: dvwa
spec:
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: 371571523880.dkr.ecr.us-east-2.amazonaws.com/dvwaxperts:<TAG>
        imagePullPolicy: "Always"
  selector:
    matchLabels:
      app: dvwa
---
kind: Service
apiVersion: v1
metadata:
  name: dvwa
spec:
  type: LoadBalancer
  selector:
    app: dvwa
  ports:
  - name: http
    port: 8081
    targetPort: 80
